openapi: 3.1.0
info:
  title: Vitrin Account Metrics API
  version: 2026.2.23
tags:
- name: Metrics
paths:
  /metrics:
    get:
      summary: Metrics
      description: Endpoint that serves Prometheus metrics.
      operationId: metrics_metrics_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
      tags:
      - Metrics
